# Generated by Django 2.2.12 on 2020-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="ccccx",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="ccvc",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
