# Generated by Django 2.2.12 on 2020-04-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200430_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='ccccx',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='ccvc',
        ),
    ]
